"""Added uuid field in models migration.

Revision ID: e38e7000c8b4
Revises: e5bbecd7216d
Create Date: 2021-12-12 02:14:39.353523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38e7000c8b4'
down_revision = 'e5bbecd7216d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'department', ['uuid'])
    op.add_column('employee', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'employee', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'uuid')
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'uuid')
    # ### end Alembic commands ###
