"""Unique model constraint migration.

Revision ID: e5bbecd7216d
Revises: 
Create Date: 2021-12-04 22:52:41.823751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bbecd7216d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='department')
    op.drop_index('name', table_name='employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'employee', ['name'], unique=False)
    op.create_index('description', 'department', ['description'], unique=False)
    # ### end Alembic commands ###
